name: Fairy

on:
  schedule:
    - cron: '0 12 * * *' # every day at noon
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Commit changes
        run: |
          git add .
          git commit --allow-empty -m "Plant grass: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
